# Assignment 7

In [0]:
# TensorFlow
import tensorflow as tf

# Helper libraries
import numpy as np
import matplotlib.pyplot as plt

print(tf.__version__)

2.2.0


**1. Given a 2D tensor of shape (?, n), extract the k (k <= n) highest values for each row into a tensor of shape (?, k). Hint: There might be a function to get the “top k” values of a tensor.**

In [0]:
# can create tensors using numpy
# np_array = np.arange(0, 20,dtype=float).reshape(5, 4)
# tens_array = tf.constant(np_array)

# or directly as follows
tens_array = tf.Variable(tf.range(0, 20, 1, dtype=float))
tens_array = tf.reshape(tens_array, shape=(5, -1))
tens_array

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.],
       [16., 17., 18., 19.]], dtype=float32)>

In [0]:
max_values = tf.reduce_max(tens_array, axis=1)
max_values

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([ 3.,  7., 11., 15., 19.], dtype=float32)>

**2. Given a tensor of shape (?, n), find the argmax in each row and return a new tensor that contains a 1 in each of the argmax’ positions, and 0s everywhere else.**

In [0]:
# creating array of argmax row-wise
max_index = tf.Variable(tf.argmax(tens_array, axis=0))
max_index

<tf.Variable 'Variable:0' shape=(4,) dtype=int64, numpy=array([4, 4, 4, 4])>

In [0]:
new_tens_zeros = tf.zeros_like(tens_array)
new_tens_ones = tf.ones_like(tens_array)

In [0]:
tf.where(tf.equal(tens_array[0],max_values[0]), new_tens_ones, new_tens_zeros)

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.]], dtype=float32)>

**3. As in 1., but instead of “extracting” the top k values, create a new tensor with shape (?, n) where all but the top k values for each row are zero. Try doing this with a 1D tensor of shape (n,) (i.e. one row) first. Getting it right for a 2D tensor is more tricky; consider this a bonus. Hint: You should look for a way to “scatter” a tensor of values into a different tensor. For two or more dimensions, you need to think carefully about the indices.**

In [0]:
tens_array = tf.Variable(tf.range(0, 20, 1, dtype=float))
tens_array = tf.reshape(tens_array, shape=(5, -1))
tens_array

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.],
       [16., 17., 18., 19.]], dtype=float32)>

In [0]:
new_tens_zeros = tf.zeros_like(tens_array)

In [0]:
max_values = tf.reduce_max(tens_array, axis=1)

In [0]:
tf.where(tf.equal(tens_array[0],max_values[0]), tens_array, new_tens_zeros)

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[ 0.,  0.,  0.,  3.],
       [ 0.,  0.,  0.,  7.],
       [ 0.,  0.,  0., 11.],
       [ 0.,  0.,  0., 15.],
       [ 0.,  0.,  0., 19.]], dtype=float32)>

**4. Implement an exponential moving average. That is, given a decay rate a and an input tensor of length T, create a new length T tensor where new[0] = input[0] and new[t] = a * new[t-1] + (1-a) * input[t] otherwise. Do not use tf.train.ExponentialMovingAverage.**

**5. Find a way to return the last element in 4. without using loops. That is, return new[T] only – you don’t need to compute the other time steps (if you can avoid it).**

**6. Given three integer tensors x, y, z all of the same (arbitrary) shape, create a new tensor that takes values from y where x is even and from z where x is odd.**

**7. Given a tensor of arbitrary and unknown shape (but at least one dimension), return 100 if the last dimension has size > 100, 12 if the last dimension has size <= 100 and > 44, and return 0 otherwise.**

**8. As 7., but also create three global counts (integers), where count i should grow by 1 if condition i happened. Run the function from 7. multiple times to test whether your counting works. Now, add a @tf.function decorator to the function from 7. Does your counter still work? If not, why not? Can you change it so it does work?**

**9. Given two 1D tensors of equal length n, create a tensor of shape (n, n) where element i,j is the ith element of the first tensor minus the jth element of the second tensor. No loops! Hint: Tensorflow supports broadcasting much like numpy.**

**10. Implement dot product attention: You are given a sequence of encoder states h of shape batch x time x features and the last decoder state s of shape batch x features. Compute the attention weights alpha where alpha[:, i] is equal to h[:, i] * s where * is the dot product between vectors (in this case we also have a batch dimension so the dot product should be between the corresponding vectors within the batch). That is, alpha should be of shape batch x time and alpha[:, i] should contain the attention weights for encoder time step i.**